targets:
  $default:
    sources:
      include:
        - $package$
        - lib/$lib$
        - lib/src/**.dart
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/src/*/**.dart
      freezed|freezed:
        generate_for:
          - lib/src/*/**.dart
        enabled: true
